    var personas = [10]; // arreglo vacio
    personas[0] = prompt("digite un numero");// acceso a una posición
    personas[1] = prompt("digite un numero");
    personas[2] = prompt("digite un numero");
    personas[3] = prompt("digite un numero");
    personas[4] = prompt("digite un numero");
    personas[5] = prompt("digite un numero");
    personas[6] = prompt("digite un numero");
    personas[8] = prompt("digite un numero");
    personas[9] = prompt("digite un numero");
    personas[10] = prompt("digite un numero");