    var number1 = prompt('Enter a number');
    var number2 = prompt('Enter a number');
    console.log("the adition between "+ number1 + " and "+ number2 + " is: ");
    console.log(parseInt(number1)+parseInt(number2));
    console.log("The subtraction between "+ number1 + " and "+ number2 + " is: ");
    console.log(parseInt(number1)-parseInt(number2));
    console.log("The multiplication between "+ number1 + " and "+ number2 + " is: ");
    console.log(parseInt(number1)*parseInt(number2));
    console.log("The division between "+ number1 + " and "+ number2 + " is: ");
    console.log(parseInt(number1)/parseInt(number2));